export const plants = [
  {
    id: "1",
    species: "Alocasia reginula",
    commonName: "Alocasia Black Velvet",
    waterNeeds: "Weekly",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "20-30°C",
    image: "/images/AlocasiaBlackVelvet.png",
    description:
      "Alocasia Black Velvet is known for its velvety, dark leaves. It prefers high humidity and bright indirect light. A stunning choice for those who appreciate unique foliage.",
    petFriendly: false,
    category: "foliage plants",
  },
  {
    id: "2",
    species: "Aloe vera",
    commonName: "Aloe Vera",
    waterNeeds: "Monthly",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "15-20°C",
    image: "/images/AloeVera.png",
    description:
      "Aloe Vera is well-known for its succulent leaves with healing properties. It requires infrequent watering and thrives in bright indirect light. A versatile plant that adds a touch of green and serves practical purposes.",
    petFriendly: false,
    category: "succulents",
  },
  {
    id: "3",
    species: "Dypsis lutescens",
    commonName: "Areca Palm",
    waterNeeds: "Every other week",
    sunlightRequirements: "Full Sun",
    size: "Large (90cm+)",
    optimalTemperature: "18-25°C",
    image: "/images/ArecaPalm.png",
    description:
      "Dypsis lutescens, commonly known as the Areca Palm, is a popular indoor palm with feathery fronds. It prefers bright indirect light and moderate watering. An excellent choice for creating a tropical oasis indoors.",
    petFriendly: false,
    category: "palms",
  },
  {
    id: "4",
    species: "Syngonium podophyllum",
    commonName: "Arrowhead Plant",
    waterNeeds: "Every other Week",
    sunlightRequirements: "Indirect Light",
    size: "Small (15cm-50cm)",
    optimalTemperature: "18-25°C",
    image: "/images/ArrowheadPlant.png",
    description:
      "Syngonium podophyllum, or Arrowhead Plant, is a versatile and easy-to-grow plant with arrow-shaped leaves. It thrives in low to medium light conditions and requires moderate watering. A charming addition to your indoor garden.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "5",
    species: "Asparagus plumosus",
    commonName: "Asparagus Fern",
    waterNeeds: "Weekly",
    sunlightRequirements: "Indirect Light",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/AsparagusFern.png",
    description:
      "Asparagus plumosus, or Asparagus Fern, is a delicate and feathery plant. It thrives in bright indirect light and requires regular watering. An elegant choice for adding a soft and lush green touch to your home.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "6",
    species: "Ocimum basilicum",
    commonName: "Basil",
    waterNeeds: "Weekly",
    sunlightRequirements: "Full Sun",
    size: "Small (15cm-50cm)",
    optimalTemperature: "18-25°C",
    image: "/images/Basil.png",
    description:
      "Basil is a fragrant herb with bright green leaves. It thrives in full sunlight and requires regular watering. A versatile herb used in various culinary dishes.",
    petFriendly: true,
    category: "herbs",
  },
  {
    id: "7",
    species: "Strelitzia reginae",
    commonName: "Bird of Paradise",
    waterNeeds: "Weekly",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "18-25°C",
    image: "/images/BirdOfParadise.png",
    description:
      "The Bird of Paradise, scientifically known as Strelitzia reginae, is a tropical plant famous for its large, banana-like leaves and vibrant, bird-like flowers. It thrives in bright indirect light and requires moderate watering. A striking and exotic addition to indoor and outdoor spaces.",
    petFriendly: false,
    category: "palms",
  },
  {
    id: "8",
    species: "Ficus microcarpa",
    commonName: "Bonsai Ficus Ginseng",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Small (15cm-50cm)",
    optimalTemperature: "20-30°C",
    image: "/images/BonsaiFicusGinseng.png",
    description:
      "Bonsai Ficus Ginseng, also known as Ficus microcarpa, is a popular choice for bonsai enthusiasts. It requires moderate watering and bright indirect light. Its unique appearance adds an artistic touch to any space.",
    petFriendly: false,
    category: "foliage plants",
  },
  {
    id: "9",
    species: "Euphorbia ingens",
    commonName: "Cactus Euphorbia",
    waterNeeds: "Monthly",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "20-30°C",
    image: "/images/CactusEuphorbia.png",
    description:
      "Euphorbia ingens, or Cactus Euphorbia, is a succulent with a tree-like appearance. It thrives in bright direct light and requires minimal watering. A unique and low-maintenance addition to your succulent collection.",
    petFriendly: true,
    category: "succulents",
  },
  {
    id: "10",
    species: "Citrofortunella microcarpa",
    commonName: "Calamondin",
    waterNeeds: "Weekly",
    sunlightRequirements: "Full Sun",
    size: "Small (15cm-50cm)",
    optimalTemperature: "20-30°C",
    image: "/images/Calamondin.png",
    description:
      "Calamondin, scientifically known as Citrofortunella microcarpa, is a small citrus tree with orange fruits. It thrives in full sunlight and requires moderate watering. Perfect for compact spaces.",
    petFriendly: true,
    category: "trees",
  },
  {
    id: "11",
    species: "Aglaonema",
    commonName: "Chinese Evergreen",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/ChineseEvergreen.png",
    description:
      "Chinese Evergreen, belonging to the Aglaonema genus, is known for its lush foliage and tolerance to low light conditions. It requires low to moderate watering, making it an excellent choice for indoor environments.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "12",
    species: "Dracaena marginata",
    commonName: "Dragon Tree",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "18-25°C",
    image: "/images/DragonTree.png",
    description:
      "The Dragon Tree, or Dracaena marginata, features long, arching leaves with a red-edged margin. It prefers bright indirect light and requires low to moderate watering. An elegant and low-maintenance choice for indoor spaces.",
    petFriendly: false,
    category: "foliage plants",
  },
  {
    id: "13",
    species: "Eucalyptus gunnii",
    commonName: "Eucalyptus Gunnii",
    waterNeeds: "Monthly",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "15-20°C",
    image: "/images/EucalyptusGunnii.png",
    description:
      "Eucalyptus Gunnii, with its aromatic leaves, is a tree native to Australia. It prefers full sunlight and low watering. Ideal for those seeking a fragrant and low-maintenance plant.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "14",
    species: "Ficus elastica",
    commonName: "Ficus Elastica",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "18-25°C",
    image: "/images/FicusElastica.png",
    description:
      "Ficus Elastica, also known as the Rubber Tree, boasts glossy, rubbery leaves. It thrives in indirect light conditions and requires low to moderate watering. A resilient and stylish indoor plant.",
    petFriendly: false,
    category: "foliage plants",
  },
  {
    id: "15",
    species: "Ficus lyrata",
    commonName: "Fiddle Fig",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "18-25°C",
    image: "/images/FiddleFig.png",
    description:
      "Fiddle Fig, or Ficus lyrata, is characterized by its large, fiddle-shaped leaves. It prefers bright indirect light and moderate watering. A statement plant for interior decor.",
    petFriendly: false,
    category: "foliage plants",
  },
  {
    id: "16",
    species: "Bromelia Guzmania",
    commonName: "Guzmania Bromeliad",
    waterNeeds: "Weekly",
    sunlightRequirements: "Indirect Light",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/GuzmaniaBromeliad.png",
    description:
      "Bromelia Guzmania, or Guzmania Bromeliad, is known for its vibrant and long-lasting flower bracts. It requires moderate to high humidity and bright indirect light. A tropical beauty that enhances any room.",
    petFriendly: true,
    category: "flowering plants",
  },
  {
    id: "17",
    species: "Hedera",
    commonName: "Ivy",
    waterNeeds: "Weekly",
    sunlightRequirements: "Partial to Full Shade",
    size: "Small (15cm-50cm)",
    optimalTemperature: "18-25°C",
    image: "/images/Ivy.png",
    description:
      "Ivy is a trailing plant with distinctive lobed leaves. It thrives in shaded areas and requires moderate watering. A classic choice for hanging baskets and vertical gardens.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "18",
    species: "Lavandula",
    commonName: "Lavender",
    waterNeeds: "Weekly",
    sunlightRequirements: "Full Sun",
    size: "Small (15cm-50cm)",
    optimalTemperature: "20-30°C",
    image: "/images/Lavender.png",
    description:
      "Lavender is a fragrant herb with spikes of purple flowers. It thrives in full sunlight and well-drained soil. Known for its aromatic properties and use in aromatherapy.",
    petFriendly: true,
    category: "herbs",
  },
  {
    id: "19",
    species: "Citrus limon",
    commonName: "Lemon Tree",
    waterNeeds: "Every other week",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "20-30°C",
    image: "/images/LemonTree.png",
    description:
      "The Lemon Tree, scientifically known as Citrus limon, bears fragrant flowers and tangy fruits. It thrives in full sunlight and requires moderate watering. A refreshing addition to any garden.",
    petFriendly: true,
    category: "flowering plants",
  },
  {
    id: "20",
    species: "Musa",
    commonName: "Mini Banana Tree",
    waterNeeds: "Weekly",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "25-30°C",
    image: "/images/MiniBananaTree.png",
    description:
      "The Mini Banana Tree, belonging to the Musa genus, features compact size and small bananas. It thrives in full sunlight and regular watering. A unique and tropical addition to your indoor garden.",
    petFriendly: false,
    category: "trees",
  },
  {
    id: "21",
    species: "Pachira aquatica",
    commonName: "Money Tree",
    waterNeeds: "Monthly",
    sunlightRequirements: "Indirect Light",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/MoneyTree.png",
    description:
      "The Money Tree, scientifically known as Pachira aquatica, is a symbol of good luck and prosperity. It thrives in indirect light conditions and requires moderate watering. A charming addition to homes and offices.",
    petFriendly: true,
    category: "succulents",
  },
  {
    id: "22",
    species: "Monstera deliciosa",
    commonName: "Monstera Deliciosa",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "20-30°C",
    image: "/images/MonsteraDeliciosa.png",
    description:
      "Monstera deliciosa, commonly known as the Monstera, is a popular and iconic houseplant with fenestrated leaves. It requires moderate watering and bright indirect light. A must-have for any plant enthusiast.",
    petFriendly: false,
    category: "foliage plants",
  },
  {
    id: "23",
    species: "Nephrolepis exaltata",
    commonName: "Nephrolepis",
    waterNeeds: "Weekly",
    sunlightRequirements: "Half-Shade",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/Nephrolepis.png",
    description:
      "Nephrolepis, commonly known as the Boston Fern, is a lush green fern with delicate fronds. It thrives in high humidity and filtered light conditions. An elegant addition to indoor spaces.",
    petFriendly: true,
    category: "ferns",
  },
  {
    id: "24",
    species: "Olea europaea",
    commonName: "Olive Tree",
    waterNeeds: "Every other week",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "15-20°C",
    image: "/images/OliveTree.png",
    description:
      "The Olive Tree, scientifically known as Olea europaea, is an iconic tree with silver-green leaves. It thrives in regions with full sunlight and requires low to moderate watering. A symbol of peace and prosperity.",
    petFriendly: true,
    category: "trees",
  },
  {
    id: "25",
    species: "Spathiphyllum",
    commonName: "Peace Lily",
    waterNeeds: "Weekly",
    sunlightRequirements: "Half-Shade",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/PeaceLily.png",
    description:
      "Spathiphyllum, commonly known as the Peace Lily, is a popular indoor plant with elegant white flowers. It prefers low to medium light and high humidity. A symbol of peace and purity for your home.",
    petFriendly: false,
    category: "flowering plants",
  },

  {
    id: "26",
    species: "Philodendron",
    commonName: "Philodendron",
    waterNeeds: "Weekly",
    sunlightRequirements: "Half-Shade",
    size: "Small (15cm-50cm)",
    optimalTemperature: "18-25°C",
    image: "/images/Philodendron.png",
    description:
      "Philodendron is a versatile and easy-to-care-for plant with heart-shaped leaves. It thrives in low to medium light conditions and requires moderate watering. A classic choice for indoor greenery.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "27",
    species: "Ananas comosus",
    commonName: "Pineapple Plant",
    waterNeeds: "Every other Week",
    sunlightRequirements: "Indirect Light",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "20-30°C",
    image: "/images/PineapplePlant.png",
    description:
      "Ananas comosus, the Pineapple Plant, is a unique tropical plant with spiky foliage. It requires moderate watering and bright indirect light. A conversation starter and a delightful addition to your plant collection.",
    petFriendly: false,
    category: "palms",
  },
  {
    id: "28",
    species: "Echeveria 'Purple Pearl'",
    commonName: "Purple Pearl Echeveria",
    waterNeeds: "Monthly",
    sunlightRequirements: "Full Sun",
    size: "Small (15cm-50cm)",
    optimalTemperature: "15-20°C",
    image: "/images/EcheveriaPurplePearl.png",
    description:
      "The Echeveria 'Purple Pearl' is a stunning succulent with rosettes of purple-tinged leaves. It prefers full sunlight and requires low watering. A beautiful addition to succulent gardens and containers.",
    petFriendly: true,
    category: "succulents",
  },
  {
    id: "29",
    species: "Rosa",
    commonName: "Rose",
    waterNeeds: "Every other week",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "15-20°C",
    image: "/images/Rose.png",
    description:
      "Rosa, or Rose, is a beloved flowering plant with a wide range of varieties. It prefers full sun and regular watering. A symbol of love and beauty, making it a timeless addition to gardens and landscapes.",
    petFriendly: true,
    category: "flowering plants",
  },
  {
    id: "30",
    species: "Rosmarinus officinalis",
    commonName: "Rosemary",
    waterNeeds: "Every other week",
    sunlightRequirements: "Full Sun",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/Rosemary.png",
    description:
      "Rosmarinus officinalis, or Rosemary, is a fragrant herb with needle-like leaves. It thrives in full sun and requires well-drained soil. A culinary and aromatic herb that adds flavor and fragrance to your garden.",
    petFriendly: true,
    category: "herbs",
  },
  {
    id: "31",
    species: "Cycas revoluta",
    commonName: "Sago Palm",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "18-25°C",
    image: "/images/SagoPalm.png",
    description:
      "Cycas revoluta, commonly known as the Sago Palm, is a slow-growing and resilient plant. It prefers bright indirect light and infrequent watering. A classic choice for adding a touch of the tropics to your space.",
    petFriendly: true,
    category: "palms",
  },
  {
    id: "32",
    species: "Schefflera arboricola",
    commonName: "Schefflera Gold Capella",
    waterNeeds: "Every other week",
    sunlightRequirements: "Indirect Light",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/ScheffleraGoldCapella.png",
    description:
      "Schefflera arboricola, or Schefflera Gold Capella, is a striking plant with variegated leaves. It requires moderate watering and bright indirect light. A decorative and air-purifying addition to your indoor space.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "33",
    species: "Sansevieria",
    commonName: "Snake Plant",
    waterNeeds: "Monthly",
    sunlightRequirements: "Half-Shade",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "15-20°C",
    image: "/images/SnakePlant.png",
    description:
      "Sansevieria, commonly known as the Snake Plant, is a hardy and low-maintenance plant. It can thrive in various light conditions and requires minimal watering. An excellent choice for beginners.",
    petFriendly: true,
    category: "succulents",
  },
  {
    id: "34",
    species: "Syngonium rose",
    commonName: "Syngonium Rose",
    waterNeeds: "Every other week",
    sunlightRequirements: "Half-Shade",
    size: "Small (15cm-50cm)",
    optimalTemperature: "18-25°C",
    image: "/images/SyngoniumRose.png",
    description:
      "Syngonium Rose is a lovely plant known for its arrow-shaped leaves. It requires moderate watering and can thrive in low to medium light conditions. A great choice for indoor greenery.",
    petFriendly: true,
    category: "foliage plants",
  },
  {
    id: "35",
    species: "Picea",
    commonName: "Spruce Tree",
    waterNeeds: "Every other week",
    sunlightRequirements: "Full Sun",
    size: "Large (90cm+)",
    optimalTemperature: "15-20°C",
    image: "/images/SpruceTree.png",
    description:
      "The Spruce Tree, belonging to the Picea genus, is a classic evergreen with needle-like leaves. It thrives in moderate watering conditions and full sunlight. A perfect choice for a festive holiday ambiance.",
    petFriendly: true,
    category: "trees",
  },
  {
    id: "36",
    species: "Thymus",
    commonName: "Thyme",
    waterNeeds: "Weekly",
    sunlightRequirements: "Full Sun",
    size: "Small (15cm-50cm)",
    optimalTemperature: "18-25°C",
    image: "/images/Thyme.png",
    description:
      "Thyme is a low-growing herb with small aromatic leaves. It prefers full sunlight and well-drained soil. Used in culinary dishes, it adds flavor and fragrance.",
    petFriendly: true,
    category: "herbs",
  },
  {
    id: "37",
    species: "Dionaea muscipula",
    commonName: "Venus Flytrap",
    waterNeeds: "Weekly",
    sunlightRequirements: "Full Sun",
    size: "Small (15cm-50cm)",
    optimalTemperature: "20-30°C",
    image: "/images/VenusFlytrap.png",
    description:
      "The Venus Flytrap is a carnivorous plant with hinged trap leaves. It thrives in full sunlight and requires high humidity. A fascinating and unique addition to your plant collection.",
    petFriendly: false,
    category: "flowering plants",
  },
  {
    id: "38",
    species: "Phalaenopsis",
    commonName: "White Orchid",
    waterNeeds: "Weekly",
    sunlightRequirements: "Indirect Light",
    size: "Medium (50cm-90cm)",
    optimalTemperature: "18-25°C",
    image: "/images/WhiteOrchid.png",
    description:
      "Phalaenopsis, or White Orchid, is an elegant and graceful flowering orchid. It requires moderate watering and bright indirect light. A symbol of beauty and sophistication, perfect for enhancing your living space.",
    petFriendly: false,
    category: "flowering plants",
  },
  {
    id: "39",
    species: "Yucca elephantipes",
    commonName: "Yucca Palm",
    waterNeeds: "Monthly",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "20-30°C",
    image: "/images/YuccaPalm.png",
    description:
      "Yucca elephantipes, or Yucca Palm, is a resilient and architectural plant with sword-like leaves. It thrives in bright indirect light and requires infrequent watering. A bold and modern addition to your indoor landscape.",
    petFriendly: true,
    category: "palms",
  },
  {
    id: "40",
    species: "Alocasia Zebrina",
    commonName: "Zebrina Plant",
    waterNeeds: "Weekly",
    sunlightRequirements: "Indirect Light",
    size: "Large (90cm+)",
    optimalTemperature: "20-30°C",
    image: "/images/ZebrinaPlant.png",
    description:
      "Alocasia Zebrina, also known as the Zebrina Plant, features striking zebra-like patterns on its stems. It prefers high humidity and bright indirect light. A stunning addition to any plant collection.",
    petFriendly: false,
    category: "foliage plants",
  },
];
