export const lightTheme = {
  background: "white",
  primaryGreen: "var(--color-green)",
  navigation: "var(--color-beige)",
  formText: "var(--color-green)",
  formField: "var(--color-grey)",
  button: "var(--color-green)",
  divider: "var(--color-grey)",
  dividerDetails: "var(--color-grey)",
  infoText: "var(--color-black)",
  popUpBackground: "rgba(255, 255, 255, 0.7)",
  popUpField: "var(--color-green)",
  popUpFieldButton: "var(--color-beige)",
};
export const darkTheme = {
  background: "#2B2E28",
  primaryGreen: "var(--color-lightGreen)",
  navigation: "#3E4438",
  formText: "var(--color-beige)",
  formField: "#2B2E28",
  button: "#3E4438",
  divider: "#3E4438",
  dividerDetails: "var(--color-beige)",
  infoText: "var(--color-beige)",
  popUpBackground: "rgba(45, 45, 40, 0.9)",
  popUpField: "#3E4438",
  popUpFieldButton: "var(--color-green)",
};
